extraction:
  cpp:
    after_prepare: 
      - python report.py 108
  cobol:
    after_prepare: 
      - python report.py 108
  csharp:
    after_prepare: 
      - python report.py 108
  java:
    after_prepare: 
      - python report.py 108
  javascript:
    after_prepare: 
      - python report.py 108
  python:
    after_prepare: 
      - python report.py 108
